route signin added and also  signin hbs
lemade3k-ironhack/vider pull request #10
Opened 2021-04-24 12:45 UTC by rebecaconte

route signin + hbs/view sign in added

2021-04-24 13:24 UTC, lemade3k requested changes
Super nice! I have just some small comments. :+1:

2021-04-24 13:24 UTC, lemade3k commented on routes/users.routes.js
> +});
In the wireframes and userflow we decided that the signin will happen on the root path "/"

basicly what allready happens in line 6-8

suggestion: delete lines 62-66

2021-04-24 13:24 UTC, lemade3k commented on routes/users.routes.js
> +router.post("/signin", (req, res, next) => {
Wish: the validations are missing. We should validate here that the user filled out the fields. You could just use the validator from line 20

```suggestion
router.post("/signin", validateEmpty, (req, res, next) => {
```

2021-04-24 13:24 UTC, lemade3k commented on routes/users.routes.js
> +              res.redirect(`/profile/${user._id}`)
Sorry I messed up the routes in the trello card. it should be: 

```suggestion
res.redirect(`/profiles/${user._id}`)
```

2021-04-24 13:24 UTC, lemade3k commented on routes/users.routes.js
> +              res.render("users/signin.hbs", { msg: "Please check if username or password are correct." })
I think it would be super nice, that if the user did an error, that the user after rendering the errors still can see what the user tipped in. It's super easy to handle with: 

```suggestion
res.render("users/signin.hbs", { username, password, msg: "Please check if username or password are correct." })
```

2021-04-24 13:24 UTC, lemade3k commented on views/users/signin.hbs
> +      <label for="password" type="password">Password:</label><br>
Haha, I also put a type="password" to the label. But it's not need here. I also fixed it in the signup form :smile: 

```suggestion
<label for="password">Password:</label><br>
```

2021-04-24 13:24 UTC, lemade3k commented on views/users/signin.hbs
> +      <label for="username">Username:</label> <br>
Question/notice: Not sure if we need the <br> tags here. We can also solve padding and margin with css. But we can also have a look on it later in the styling process

2021-04-24 15:04 UTC, rebecaconte commented on routes/users.routes.js
> +});
yeap, I remember!

2021-04-24 15:04 UTC, rebecaconte commented on routes/users.routes.js
> +router.post("/signin", (req, res, next) => {
Ops! fixed! :D

2021-04-24 15:04 UTC, rebecaconte commented on routes/users.routes.js
> +              res.redirect(`/profile/${user._id}`)
haha no worries!

2021-04-24 15:05 UTC, rebecaconte commented on views/users/signin.hbs
> +      <label for="username">Username:</label> <br>
I left this one for now. We can always remove it later! :D

2021-04-26 07:58 UTC, lemade3k approved these changes

2021-04-26 07:58 UTC, merged